title: Chinonso Ibiam # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C4D03AQHHQWIf0mvQEA/profile-displayphoto-shrink_800_800/0/1661155499854?e=1675900800&v=beta&t=_5PUu0yBZs5t3XoqiCkrorsl3S65RtPTTkC7bl-l0bE" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/chinonso-ibiam-059850174/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

